[project]
name = "oldap-mediaserver"
version = "0.1.0"
description = ""
authors = [
    {name = "lrosenth",email = "lukas.rosenthaler@pm.me"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "flask (==3.1.2)",
    "pyvips (==3.0.0)",
    "requests (==2.32.5)",
    "flask-cors (>=6.0.1,<7.0.0)",
    "pyjwt (>=2.10.1)",
    "gunicorn (>=23.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
